package me.saket.telephoto.zoomable

import androidx.compose.runtime.Immutable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.TransformOrigin
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.ScaleFactor

// todo: doc.
/**
 * Graphics transformations generated by [Modifier.zoomable] for its content.
 *
 * By default, these are automatically applied by `Modifier.zoomable()`, but this
 * behavior can be disabled using [ZoomableState.autoApplyTransformations] if the
 * content has its own bespoke way of consuming pan & zoom changes.
 */
@Immutable
data class ZoomableContentTransformation(
  val contentSize: Size,
  val scale: ScaleFactor,
  val rotationZ: Float,
  val offset: Offset,
  val transformOrigin: TransformOrigin = TransformOriginAtZero,
  val isSpecified: Boolean,
) {
  val isUnspecified: Boolean get() = !isSpecified

  companion object {
    private val TransformOriginAtZero = TransformOrigin(0f, 0f)
  }
}

// todo: doc.
internal fun Modifier.applyTransformation(transformation: ZoomableContentTransformation): Modifier {
  // todo: optimize these. use graphicsLayer only when necessary.
  return graphicsLayer {
    scaleX = transformation.scale.scaleX
    scaleY = transformation.scale.scaleY
    rotationZ = transformation.rotationZ
    translationX = transformation.offset.x
    translationY = transformation.offset.y
    transformOrigin = transformation.transformOrigin
  }
}
