package me.saket.telephoto.zoomable

import androidx.compose.runtime.Immutable
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.TransformOrigin
import androidx.compose.ui.layout.ScaleFactor

/**
 * Graphics transformations generated by [Modifier.zoomable] for its content.
 *
 * By default, these are automatically applied by `Modifier.zoomable()`, but this
 * behavior can be disabled using [ZoomableState.autoApplyTransformations] if the
 * content has its own bespoke way of consuming pan & zoom changes.
 */
@Immutable
data class ZoomableContentTransformation(
  val scale: ScaleFactor,
  val rotationZ: Float,
  val offset: Offset,
  val transformOrigin: TransformOrigin = TransformOriginAtZero,
) {
  companion object {
    private val TransformOriginAtZero = TransformOrigin(0f, 0f)
  }
}
