package me.saket.telephoto.subsamplingimage.internal

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.toAndroidRectF
import androidx.compose.ui.graphics.toComposeRect
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.IntRect
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.toRect
import androidx.core.graphics.toRect
import assertk.assertThat
import assertk.assertions.isEqualTo
import me.saket.telephoto.subsamplingimage.internal.ExifMetadata.ImageOrientation
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

// Disclaimer: mostly generated by AI.
// I'm not sure how useful these tests are. This file looks like a giant wall of numbers
// that are hard to read. Telephoto already has screenshot tests that are easier to diff.
@RunWith(RobolectricTestRunner::class)
class RotationTest {
  @Test fun rotate_entire_image() {
    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 4032, y = 3024)
    ).let { original ->
      assertThat(original.rotateRegionBy(90, parent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 3024, y = 4032)
        )
      )
    }

    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 3024, y = 4032)
    ).let { original ->
      assertThat(original.rotateRegionBy(-90, parent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 4032, y = 3024)
        )
      )
    }

    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 3024, y = 4032),
    ).let { original ->
      assertThat(original.rotateRegionBy(-90, original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 4032, y = 3024),
        )
      )
    }

    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    ).let { original ->
      assertThat(original.rotateRegionBy(90, original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 800, y = 1600)
        )
      )
    }
  }

  @Test fun rotate_parts_of_an_image() {
    val landscape = IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    )

    assertThat(
      IntRect(
        topLeft = landscape.topCenter,
        bottomRight = landscape.centerRight,
      ).rotateRegionBy(90, landscape)
    ).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 400, y = 800),
        bottomRight = IntOffset(x = 800, y = 1600),
      )
    )
    assertThat(
      IntRect(
        topLeft = landscape.topCenter,
        bottomRight = IntOffset(x = 1200, y = 400),
      ).rotateRegionBy(180, landscape)
    ).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 400, y = 400),
        bottomRight = IntOffset(x = 800, y = 800),
      )
    )
    assertThat(
      IntRect(
        offset = IntOffset(x = 400, y = 400),
        size = IntSize(400, 400)
      ).rotateRegionBy(270, landscape)
    ).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 400, y = 800),
        bottomRight = IntOffset(x = 800, y = 1200),
      )
    )
    assertThat(
      IntRect(
        topLeft = landscape.topCenter,
        bottomRight = landscape.centerRight,
      )
        .rotateRegionBy(90, landscape)
        .rotateRegionBy(90, landscape)
        .rotateRegionBy(90, landscape)
        .rotateRegionBy(90, landscape)
    ).isEqualTo(
      IntRect(
        topLeft = landscape.topCenter,
        bottomRight = landscape.centerRight,
      )
    )

    val portrait = IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 800, y = 1600)
    )
    val bottomLeftRect = IntRect(
      topLeft = portrait.centerLeft,
      bottomRight = portrait.bottomCenter,
    )
    assertThat(bottomLeftRect.rotateRegionBy(-90, portrait)).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 800, y = 400),
        bottomRight = IntOffset(x = 1600, y = 800)
      )
    )

    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 5, y = 6)
    ).let { parent ->
      val rect = IntRect(
        topLeft = IntOffset(1, 2),
        bottomRight = IntOffset(2, 4),
      )

      assertThat(rect.rotateRegionBy(-90, parent)).isEqualTo(
        IntRect(
          topLeft = IntOffset(2, 3),
          bottomRight = IntOffset(4, 4),
        )
      )
    }
  }

  @Test fun flip_entire_image() {
    // Horizontal flip - when flipping the entire image, it should stay in the same bounds
    // but the internal content would be mirrored (this test is about bounds transformation)
    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 4032, y = 3024)
    ).let { original ->
      assertThat(original.flipRegionHorizontally(parent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 4032, y = 3024)
        )
      )
    }

    // Vertical flip (180° rotation + horizontal flip) - dimensions stay same
    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 3024, y = 4032)
    ).let { original ->
      assertThat(original.flipVertically(unRotatedParent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 3024, y = 4032)
        )
      )
    }

    // Test horizontal flip with a sub-rectangle to see actual coordinate transformation
    val landscape = IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    )

    // Right half should become left half when flipped
    val rightHalf = IntRect(
      topLeft = IntOffset(x = 800, y = 0),
      bottomRight = IntOffset(x = 1600, y = 800)
    )

    assertThat(rightHalf.flipRegionHorizontally(parent = landscape)).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 0, y = 0),
        bottomRight = IntOffset(x = 800, y = 800)
      )
    )

    // Transpose (90° + horizontal flip) - dimensions swap like 90° rotation
    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    ).let { original ->
      assertThat(original.transposeBy(unRotatedParent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 800, y = 1600)
        )
      )
    }

    // Transverse (270° + horizontal flip) - dimensions swap like 270° rotation
    IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    ).let { original ->
      assertThat(original.transverseBy(unRotatedParent = original)).isEqualTo(
        IntRect(
          topLeft = IntOffset.Zero,
          bottomRight = IntOffset(x = 800, y = 1600)
        )
      )
    }
  }

  @Test fun flip_parts_of_an_image() {
    val landscape = IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = 1600, y = 800)
    )

    // Test simple horizontal flip - mirror X coordinates
    val rightQuadrant = IntRect(
      topLeft = IntOffset(x = 800, y = 0),
      bottomRight = IntOffset(x = 1600, y = 400),
    )
    assertThat(rightQuadrant.flipRegionHorizontally(parent = landscape)).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 0, y = 0),        // X mirrored: 1600 - 1600 = 0
        bottomRight = IntOffset(x = 800, y = 400), // X mirrored: 1600 - 800 = 800
      )
    )

    // Test vertical flip - mirror both X and Y coordinates
    val centerRect = IntRect(
      topLeft = IntOffset(x = 400, y = 200),
      bottomRight = IntOffset(x = 1200, y = 600),
    )
    assertThat(centerRect.flipVertically(unRotatedParent = landscape)).isEqualTo(
      IntRect(
        topLeft = IntOffset(x = 400, y = 200),    // X: 1600-1200=400, Y: 800-600=200
        bottomRight = IntOffset(x = 1200, y = 600), // X: 1600-400=1200, Y: 800-200=600
      )
    )

    // Test transpose using actual rotateBy + flip logic
    val bottomLeftQuad = IntRect(
      topLeft = IntOffset(x = 0, y = 400),
      bottomRight = IntOffset(x = 800, y = 800),
    )

    // First rotate by 90°, then flip horizontally
    val rotated90 = bottomLeftQuad.rotateRegionBy(90, landscape)
    val transposed = rotated90.flipRegionHorizontally(
      parent = IntRect(IntOffset.Zero, IntSize(landscape.height, landscape.width)),
    )

    assertThat(bottomLeftQuad.transposeBy(landscape)).isEqualTo(transposed)

    // Test transverse using actual rotateBy + flip logic
    val centerSquare = IntRect(
      offset = IntOffset(x = 400, y = 200),
      size = IntSize(400, 400)
    )

    // First rotate by 270°, then flip horizontally
    val rotated270 = centerSquare.rotateRegionBy(270, landscape)
    val transversed = rotated270.flipRegionHorizontally(
      parent = IntRect(IntOffset.Zero, IntSize(landscape.height, landscape.width)),
    )

    assertThat(centerSquare.transverseBy(landscape)).isEqualTo(transversed)

    // Test chaining operations
    assertThat(
      rightQuadrant
        .flipRegionHorizontally(parent = landscape)
        .flipRegionHorizontally(parent = landscape)
    ).isEqualTo(rightQuadrant)
  }

  @Test fun `rotation matrix for filling viewport bounds when exif orientation is 90 degrees`() {
    val imageBounds = Rect(Offset.Zero, Size(1328f, 1000f))
    val matrix = createRotationMatrix(
      bitmapSize = imageBounds.size,
      exif = ExifMetadata(ImageOrientation.Orientation90, flippedHorizontally = false),
      bounds = Size(1080f, 2400f),
    )

    assertThat(matrix.mapRect(imageBounds)).isEqualTo(
      Rect(0f, 0f, 1080f, 2400f)
    )
  }

  @Test fun `rotation matrix for filling viewport bounds when exif orientation is none`() {
    val imageBounds = Rect(Offset.Zero, Size(1000f, 1328f))
    val matrix = createRotationMatrix(
      bitmapSize = imageBounds.size,
      exif = ExifMetadata(ImageOrientation.None, flippedHorizontally = false),
      bounds = Size(1080f, 2400f),
    )

    assertThat(matrix.mapRect(imageBounds)).isEqualTo(
      Rect(0f, 0f, 1080f, 2400f)
    )
  }

  @Test fun `rotation matrix for upscaling an image`() {
    val imageBounds = Rect(Offset.Zero, Size(250f, 167f))
    val matrix = createRotationMatrix(
      bitmapSize = imageBounds.size,
      exif = ExifMetadata(ImageOrientation.None, flippedHorizontally = false),
      bounds = Size(1080f, 2400f),
    )

    assertThat(matrix.mapRect(imageBounds)).isEqualTo(
      Rect(0f, 0f, 1080f, 2400f)
    )
  }

  @Test fun `rotation matrix maintains pixel perfect alignment`() {
    // Test with various image sizes that aren't multiples of the viewport.
    val viewportBounds = Size(1080f, 2400f)
    val imageSizes = listOf(
      Size(250f, 167f),
      Size(333f, 555f),    // Odd dimensions
      Size(1000f, 1328f),  // Normal image with 0° rotation
      Size(1328f, 1000f),  // Normal image with 90° rotation
    )

    for (imageSize in imageSizes) {
      for (orientation in ImageOrientation.entries) {
        val imageBounds = Rect(Offset.Zero, imageSize)
        val matrix = createRotationMatrix(
          bitmapSize = imageSize,
          exif = ExifMetadata(orientation, flippedHorizontally = false),
          bounds = viewportBounds
        )

        val mappedRect = matrix.mapRect(imageBounds)
        try {
          assertThat(mappedRect).isEqualTo(
            Rect(0f, 0f, viewportBounds.width, viewportBounds.height)
          )
        } catch (e: Throwable) {
          println("Failed for $imageSize at $orientation")
          throw e
        }
      }
    }
  }

  @Test fun `rotation matrix ensures no gaps between tiles`() {
    val viewportBounds = Size(1080f, 2400f)
    val imageSize = Size(2700f, 6000f)

    val tiles = ImageRegionTileGrid.generate(
      viewportSize = viewportBounds.discardFractionalParts(),
      unscaledImageSize = imageSize.discardFractionalParts(),
    ).foreground.values.single()

    val matrix = createRotationMatrix(
      bitmapSize = imageSize,
      exif = ExifMetadata(ImageOrientation.None, flippedHorizontally = false),
      bounds = viewportBounds
    )

    val mappedTiles = tiles.map { tile ->
      matrix.mapRect(tile.bounds.toRect())
    }

    // Verify no gaps.
    val totalArea = mappedTiles.sumOf { (it.width * it.height).toDouble() }.toFloat()
    val expectedArea = viewportBounds.width * viewportBounds.height
    assertThat(totalArea).isEqualTo(expectedArea)
  }

  private fun android.graphics.Matrix.mapRect(rect: Rect): Rect {
    val rectF = rect.toAndroidRectF()
    mapRect(rectF)
    return rectF.toRect().toComposeRect()
  }
}

private fun IntRect.flipVertically(unRotatedParent: IntRect): IntRect {
  return IntRect(
    topLeft = IntOffset(
      x = unRotatedParent.width - bottomRight.x,
      y = unRotatedParent.height - bottomRight.y
    ),
    bottomRight = IntOffset(
      x = unRotatedParent.width - topLeft.x,
      y = unRotatedParent.height - topLeft.y
    )
  )
}

private fun IntRect.transposeBy(unRotatedParent: IntRect): IntRect {
  if (this == unRotatedParent) {
    return IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = unRotatedParent.height, y = unRotatedParent.width)
    )
  }

  // Transpose = 90° rotation + horizontal flip
  val rotated = rotateRegionBy(90, unRotatedParent)
  val rotatedParent = IntRect(IntOffset.Zero, IntSize(unRotatedParent.height, unRotatedParent.width))
  return rotated.flipRegionHorizontally(parent = rotatedParent)
}

private fun IntRect.transverseBy(unRotatedParent: IntRect): IntRect {
  if (this == unRotatedParent) {
    return IntRect(
      topLeft = IntOffset.Zero,
      bottomRight = IntOffset(x = unRotatedParent.height, y = unRotatedParent.width)
    )
  }

  // Transverse = 270° rotation + horizontal flip
  val rotated = rotateRegionBy(270, unRotatedParent)
  val rotatedParent = IntRect(IntOffset.Zero, IntSize(unRotatedParent.height, unRotatedParent.width))
  return rotated.flipRegionHorizontally(parent = rotatedParent)
}
