plugins {
  id("me.saket.android.library")
  id("me.saket.library.publishing")
  id("me.saket.kotlin.android")
  id("me.saket.compose")
  id("me.saket.android.test")
  alias(libs.plugins.paparazzi)
}

android {
  namespace "me.saket.telephoto.zoomable.image.coil"
}

dependencies {
  api(projects.zoomableImage.core)
  implementation(projects.zoomableImage.subSamplingImage)

  api(libs.coil.compose)
  implementation(libs.accompanist.drawablePainter)

  testImplementation(libs.junit)
  testImplementation(libs.coil.test)
  testImplementation(libs.compose.ui.material3)
  testImplementation(libs.testParamInjector)

  androidTestImplementation(projects.testUtil)
  androidTestImplementation(libs.turbine)
  androidTestImplementation(libs.molecule.runtime)
  androidTestImplementation(libs.okhttp.mockWebServer)
  androidTestImplementation(libs.coil.gif)
  androidTestImplementation(libs.coil.svg)
  androidTestImplementation(libs.coil.test)
  androidTestImplementation(libs.okio.fakeFileSystem)
  androidTestImplementation(libs.modernstorage)
}
